set windows-shell := ["powershell.exe", "-c"]

_default:
    @just --choose

singbox-mihomo-setup:
    # Download
    iwr "https://ghfast.top/https://github.com/winsw/winsw/releases/latest/download/WinSW-x64.exe" -O winsw.exe
    iwr "https://ghfast.top/https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip" -O dist.zip
    Expand-Archive -Path "dist.zip"; mi "dist\dist" "ui"; ri "dist.zip", "dist"
    # Create directory
    New-Item $HOME\services\subs\state -ItemType Directory -Force
    Move-Item ui $HOME\services\subs\state
    # Copy services
    Copy-Item ..\mofa\config.yaml $HOME\services\subs
    Copy-Item sb-service.xml, mihomo-service.xml $HOME\services\subs
    Copy-Item winsw.exe $HOME\services\subs\sb-service.exe
    Copy-Item winsw.exe $HOME\services\subs\mihomo-service.exe

rclone-services:
    if (!(Test-Path "winsw.exe")) \
    { iwr "https://ghfast.top/https://github.com/winsw/winsw/releases/latest/download/WinSW-x64.exe" -O winsw.exe } ; \
    New-Item $HOME\services\rclone -ItemType Directory -Force
    Copy-Item rclone-infini-service.xml $HOME\services\rclone
    Copy-Item rclone-koofr-service.xml $HOME\services\rclone
    Copy-Item winsw.exe $HOME\services\rclone\rclone-infini-service.exe
    Copy-Item winsw.exe $HOME\services\rclone\rclone-koofr-service.exe
    Remove-Item winsw.exe
